### ISSUE TITLE
"What is Influence Mapping?" info should have more visibility on the site

### ISSUE THREAD

**Issue by jmatsushita** [iilab/influencemapping-toolbox#7]
Thinking about newcomers and a phrase I believe is key: "You can be an influence mapper and not even know it yet", I agree with Joe that the "What is Influence Mapping?" info should have more visibility on the site. Maybe on the front page, or as a primary category at the Menu.

**Comment by jmatsushita** [comment]
> this could get more prominent placement than on the 'About' page, which could be a narrower 'about the toolbox'  section. Front page?

**Comment by iamkat** [comment]
I'll go through the document and move the content into the relevant .md files

**Comment by iamkat** [comment]
I'm going to move some of this info to the Front Page but we need to amend the design. I'll do the words for now and the design elements I will make a separate issue.

**Comment by iamkat** [comment]
I'm keeping the longer "what is influence mapping" part on the about page as I think there's stuff in there that doesn't fit on the front page
